### ISSUE TITLE
Cannot build the latest version

### ISSUE THREAD

**Issue by ningyu18** [thsa/datawarrior#1]
I cannot build the latest version of the source due to many missing dependencies, e.g. the com.acetelion.research.calc and com.acetelion.research.chem.descriptor Java packages. The previous version I was able to build successfully is v4.7.2 which I downloaded from a different site.

**Comment by thsa** [comment]
I just creates an empty test directory on Ubuntu, cloned the repo with:

git clone https://github.com/thsa/datawarrior.git

The I ran './buildDataWarrior' and './runDataWarrior' after which DataWarrior launched...

I used JRE 8 191. If you compile and run on Windows, you have to adapt the syntax in the scripts slightly (path and jar separators). If you miss com.acetelion.research.calc and com.acetelion.research.chem.descriptor, then it looks like you use an older OpenChemLib version. If you don't use the openchemlib.jar files included in the repo and build it yourself from the openchemlib repo, then please check, whether you have pulled the newest version.

Thomas
________________________________
Von: ningyu18 <notifications@github.com>
Gesendet: Freitag, 29. Januar 2021 00:45
An: thsa/datawarrior <datawarrior@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [thsa/datawarrior] Cannot build the latest version (#1)


I cannot build the latest version of the source due to many missing dependencies, e.g. the com.acetelion.research.calc and com.acetelion.research.chem.descriptor Java packages. The previous version I was able to build successfully is v4.7.2 which I downloaded from a different site.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Fissues%2F1&data=04%7C01%7Cthomas.sander%40idorsia.com%7Cb05fc0886afc45fd307108d8c3e6bbaa%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637474743045616885%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sj7sXowk%2BrhiUlAnwZ3uAkaJ%2BtAMFXySkIgqd6515%2BA%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBWZXZMJHUEF5PQ6E53S4HZH3ANCNFSM4WX55UNQ&data=04%7C01%7Cthomas.sander%40idorsia.com%7Cb05fc0886afc45fd307108d8c3e6bbaa%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637474743045626840%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=tw7xQED8aULoRN6Ket1wyFE2zXUPZneZTIBHFDW9eWY%3D&reserved=0>.

The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by ningyu18** [comment]
Thank you. By following your instructions and with a little tweaking, I was able to import the latest version of the source as an Eclipse project.
