### ISSUE TITLE
Compiling returns an error - commit a8159f1 "fixed issue with free valence check causing trouble in Reactor [...]"

### ISSUE THREAD

**Issue by mattiafelice-palermo** [thsa/datawarrior#5]
Hi Thomas,

I'm writing regarding the forum post on [Reaction enumeration with aromaticity](https://openmolecules.org/forum/index.php?t=msg&th=490&start=0&).

As mentioned in one of the last comments, I run into a bug using the development version. I get an error when switching from the "Generic Reaction" to "Reactants" tab in the Enumerate Combinatorial Library dialog window, after drawing some general reactant structures.

I tried to do some troubleshooting and ended compiling Datawarrior on my machine. I installed Bellsoft Liberica OpenJDK 8 with JavaFX and tried compiling the code, but I get the following error:

> ./src/com/actelion/research/datawarrior/task/chem/clib/UIDelegateCLib.java:191: error: constructor SubstructureFilter in class SubstructureFilter cannot be applied to given types;
> 				mReactantPaneList.get(i).setCompoundFilter(new SubstructureFilter(reaction.getReactant(i), 
 SSearcher.cMatchDBondToDelocalized));                                      
>
>   required: StereoMolecule
>   found: StereoMolecule,int
>   reason: actual and formal argument lists differ in length

I think this is one of the modifications that were made to the code to account for delocalized/aromatic bonds in generic reactant structure. Trying to run the executable resulted in an uncaught exception when opening the Enumerate Combinatorial Library panel.

I tried removing the second argument "SSearcher.cMatchDBondToDelocalized" from the call to the setCompoundFilter function and the program compiles and runs without any error (I guess the setCompoundFilter signature has not been updated to account for a second argument).

I tried the Combinatorial functionality with the so compiled version of the program and it seems to work fine with the delocalized version of the generic reactant, but it does not work with the "double bond + is aromatic bond" strategy.

Do you think it is something that can be fixed?

I apologize for writing a third post about this! I just wanted to share what I have found in the hope it might be helpful. Please let me know if you need any further information.

Thank you so much for your help!

Mattia

**Comment by thsa** [comment]
Dear Mattia,

thank you for the mail and the comment on the forum. I didn't answer yet, because I currently need to work on some important Idorsia specific stuff. I will look into it latest next week, hopefully earlier. If you update the datawarrior project (git pull), then it should compile now. The problem was that I missed to update the openchemlib.jar after fixing the valence issue. Sorry for that. Usually, I test building the project.

Currently, I am not sure, whether there will be a fully satisfactory solution with the delocalized bonds: Most likely I cannot remove the valence check. At the same time a delocalized bond sometimes occupies 1 and sometimes 2 valences, depending on the real molecule it matches on. Possibly, I can make a relaxed check and test valences, when creating the products... I need to play with options. And I will let you know...

I will just now deploy an update, but doesn't change the combichem issue. It just adds custom thresholds for colors...

Best wishes,

Thomas
________________________________
Von: Mattia Felice Palermo ***@***.***>
Gesendet: Montag, 7. Juni 2021 16:57
An: thsa/datawarrior ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [thsa/datawarrior] Compiling returns an error - commit a8159f1 "fixed issue with free valence check causing trouble in Reactor [...]" (#5)


Hi Thomas,

I'm writing regarding the forum post on Reaction enumeration with aromaticity<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fopenmolecules.org%2Fforum%2Findex.php%3Ft%3Dmsg%26th%3D490%26start%3D0%26&data=04%7C01%7Cthomas.sander%40idorsia.com%7Cf8e6fb7adb854b26e1c708d929c48dbb%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637586746428624214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KrhEbZ6iSEsevAvCv4yWxbgPWi8VQJSIcQYlY68OVh4%3D&reserved=0>.

As mentioned in one of the last comments, I run into a bug using the development version. I get an error when switching from the "Generic Reaction" to "Reactants" tab in the Enumerate Combinatorial Library dialog window, after drawing some general reactant structures.

I tried to do some troubleshooting and ended compiling Datawarrior on my machine. I installed Bellsoft Liberica OpenJDK 8 with JavaFX and tried compiling the code, but I get the following error:

./src/com/actelion/research/datawarrior/task/chem/clib/UIDelegateCLib.java:191: error: constructor SubstructureFilter in class SubstructureFilter cannot be applied to given types;
mReactantPaneList.get(i).setCompoundFilter(new SubstructureFilter(reaction.getReactant(i),
SSearcher.cMatchDBondToDelocalized));

required: StereoMolecule
found: StereoMolecule,int
reason: actual and formal argument lists differ in length

I think this is one of the modifications that were made to the code to account for delocalized/aromatic bonds in generic reactant structure. Trying to run the executable resulted in an uncaught exception when opening the Enumerate Combinatorial Library panel.

I tried removing the second argument "SSearcher.cMatchDBondToDelocalized" from the call to the setCompoundFilter function and the program compiles and runs without any error (I guess the setCompoundFilter signature has not been updated to account for a second argument).

I tried the Combinatorial functionality with the so compiled version of the program and it seems to work fine with the delocalized version of the generic reactant, but it does not work with the "double bond + is aromatic bond" strategy.

Do you think it is something that can be fixed?

I apologize for writing a third post about this! I just wanted to share what I have found in the hope it might be helpful. Please let me know if you need any further information.

Thank you so much for your help!

Mattia

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Fissues%2F5&data=04%7C01%7Cthomas.sander%40idorsia.com%7Cf8e6fb7adb854b26e1c708d929c48dbb%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637586746428624214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BoXV0y5dBhLl2hehRRlJLYFYqhBvd0wsyyUzYfXjItc%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBV3WLXEJFKIHKWTEKDTRTM5BANCNFSM46H3IVRQ&data=04%7C01%7Cthomas.sander%40idorsia.com%7Cf8e6fb7adb854b26e1c708d929c48dbb%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637586746428624214%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZxSPgkeX7uEy%2Fsq4bZ6AYACnM5pRdoGO7w%2BiOsjW%2F7w%3D&reserved=0>.

The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by mattiafelice-palermo** [comment]
Hi Thomas,

thanks for answering so quickly. By all means, I understand your priority is of course your company, I did not mean to be pushy :)

I really appreciate your effort and sounds great for the future update.

Once it's done, if you need some testing on the functionality just let me know. 

Best wishes,

Mattia

P.s.: for future reference when you'll have the chance to work on the issue, I have just tried the updated version. It seems to be working, but I noticed that once I set the "is aromatic bond" option, for it to be recognized I need to do some other action first (adding a bong, reopening the bond option and clicking ok again, etc.).
