### ISSUE TITLE
add .tsv extension to DataWarrior compatible data files

### ISSUE THREAD

**Issue by rczerminski-valo** [thsa/datawarrior#9]
Would it be possible to add `.tsv` extension? I know that currently TAB separated files with `.txt` extension are supported, so it is convenience/UX feature request. If at all possible I would appreciate it very much.

**Comment by thsa** [comment]
tsv is already in the current source code and, thus, in the development update that can be downloaded from the official download page. The link appears after clicking 'read and understood' in the fineprint.
________________________________
Von: rczerminski-valo ***@***.***>
Gesendet: Mittwoch, 31. August 2022 16:39
An: thsa/datawarrior ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [thsa/datawarrior] add .tsv extension to DataWarrior compatible data files (Issue #9)


Would it be possible to add .tsv extension? I know that currently TAB separated files with .txt extension are supported, so it is convenience/UX feature request. If at all possible I would appreciate it very much.

—
Reply to this email directly, view it on GitHub<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Fissues%2F9&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ca201cef340b245893dbb08da8b5e92dd%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637975535544909684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3od0%2F5nQR4BLfF%2FgbQKipJs8dlUvdExzX7crx7ZY41w%3D&reserved=0>, or unsubscribe<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBV7M6QPZDK2JVQNCATV35VBBANCNFSM6AAAAAAQBOGL2E&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ca201cef340b245893dbb08da8b5e92dd%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637975535544909684%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3bxmmllKgX6tHailF%2Fdfhk842oi%2B%2Fo2JjwaCVbv0r9E%3D&reserved=0>.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

________________________________
The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by rczerminski-valo** [comment]
That's awesome!

I have some issues with the build (on mac). Here is what I did:

```
brew install java
brew info java
sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
git clone git@github.com:thsa/datawarrior.git
cd datawarrior
./buildDataWarrior >& buildDataWarrior.log
./runDataWarrior >& runDataWarrior.log
```

See attached log files:

[buildDataWarrior.log](https://github.com/thsa/datawarrior/files/9472223/buildDataWarrior.log)
[runDataWarrior.log](https://github.com/thsa/datawarrior/files/9472226/runDataWarrior.log)

**Comment by thsa** [comment]
it seems that your JDK doesn't contain JavaFX. I personally use liberica-full JDK 8. Only the 'full' version contains JFX. However, any JDK8 that include JFX will do.
________________________________
Von: rczerminski-valo ***@***.***>
Gesendet: Donnerstag, 1. September 2022 20:00
An: thsa/datawarrior ***@***.***>
Cc: Thomas Sander ***@***.***>; Comment ***@***.***>
Betreff: Re: [thsa/datawarrior] add .tsv extension to DataWarrior compatible data files (Issue #9)


That's awesome!

I have some issues with the build (on mac). Here is what I did:

brew install java
brew info java
sudo ln -sfn /usr/local/opt/openjdk/libexec/openjdk.jdk /Library/Java/JavaVirtualMachines/openjdk.jdk
git clone ***@***.***:thsa/datawarrior.git
cd datawarrior
./buildDataWarrior >& buildDataWarrior.log
./runDataWarrior >& runDataWarrior.log


See attached log files:

buildDataWarrior.log<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Ffiles%2F9472223%2FbuildDataWarrior.log&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ccbf4503d1a5e4a7d894008da8c43dc30%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976520321471221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VBkd1HyAOywaVQwrHd%2Fof21Ec1QQCqEEzyiLkRf2zl8%3D&reserved=0>
runDataWarrior.log<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Ffiles%2F9472226%2FrunDataWarrior.log&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ccbf4503d1a5e4a7d894008da8c43dc30%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976520321471221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EErLFe6crtgIILElPfzG15u79DXlJzDxFv8sXP6y8qk%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Fissues%2F9%23issuecomment-1234609248&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ccbf4503d1a5e4a7d894008da8c43dc30%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976520321471221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=kaj3LRkm0uPhvOkXnIGE07Cib1MDaM1P92abw1HUNVg%3D&reserved=0>, or unsubscribe<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBRASZC6PTGJECNKLCDV4DVL3ANCNFSM6AAAAAAQBOGL2E&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ccbf4503d1a5e4a7d894008da8c43dc30%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976520321471221%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fxCpun%2FYyYW20DzGlfvbadblACQX3ywZ7JDceOXYcuU%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

________________________________
The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by rczerminski-valo** [comment]
I installed `liberica-jdk-8-full`, but I still cannot build:

```
$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/liberica-jdk-8-full.jdk/Contents/Home/
$ $JAVA_HOME/bin/javac -d ./bin -sourcepath ./src:./stubs -classpath "./lib/*" src/com/actelion/research/datawarrior/DataWarriorOSX.java >& javac.log
rm -r bin/chemaxon
# rm: bin/chemaxon: No such file or directory
$JAVA_HOME/bin/jar -cfm datawarrior.jar manifest_additions.txt -C ./bin .
rm -r bin
# feeling lucky :)
$JAVA_HOME/bin/java -classpath "datawarrior.jar:./lib/*" com.actelion.research.datawarrior.DataWarriorOSX
Error: Could not find or load main class com.actelion.research.datawarrior.DataWarriorOSX
```
[javac.log](https://github.com/thsa/datawarrior/files/9472540/javac.log)

**Comment by thsa** [comment]
the original buildDataWarrior script uses the DataWarriorLinux application class, which is a kind of generic and runs on OSX as well. I have now added the needed files to also compile with the DataWarriorOSX as main application class, which, admittedly, makes more sense on the Mac. Please use buildDataWarriorOSX and runDataWarriorOSX...
________________________________
Von: rczerminski-valo ***@***.***>
Gesendet: Donnerstag, 1. September 2022 20:54
An: thsa/datawarrior ***@***.***>
Cc: Thomas Sander ***@***.***>; Comment ***@***.***>
Betreff: Re: [thsa/datawarrior] add .tsv extension to DataWarrior compatible data files (Issue #9)


I installed liberica-jdk-8-full, but I still cannot build:

$ export JAVA_HOME=/Library/Java/JavaVirtualMachines/liberica-jdk-8-full.jdk/Contents/Home/
$ $JAVA_HOME/bin/javac -d ./bin -sourcepath ./src:./stubs -classpath "./lib/*" src/com/actelion/research/datawarrior/DataWarriorOSX.java >& javac.log
rm -r bin/chemaxon
# rm: bin/chemaxon: No such file or directory
$JAVA_HOME/bin/jar -cfm datawarrior.jar manifest_additions.txt -C ./bin .
rm -r bin
# feeling lucky :)
$JAVA_HOME/bin/java -classpath "datawarrior.jar:./lib/*" com.actelion.research.datawarrior.DataWarriorOSX
Error: Could not find or load main class com.actelion.research.datawarrior.DataWarriorOSX


javac.log<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Ffiles%2F9472540%2Fjavac.log&data=05%7C01%7Cthomas.sander%40idorsia.com%7C24eee3fc60d040f1f70908da8c4b7879%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976553010671945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jliMxnDKIvh2J8%2FuwjZowJI2ocWAfv9OomDWkeXun%2Bo%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Fissues%2F9%23issuecomment-1234660576&data=05%7C01%7Cthomas.sander%40idorsia.com%7C24eee3fc60d040f1f70908da8c4b7879%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976553010671945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oyyzgBdqaGzxrA80OqIgA19JDWGNBmeTQI6iymRcHuY%3D&reserved=0>, or unsubscribe<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBRBGDDLDCMJDWQU4WTV4D3YFANCNFSM6AAAAAAQBOGL2E&data=05%7C01%7Cthomas.sander%40idorsia.com%7C24eee3fc60d040f1f70908da8c4b7879%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637976553010671945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B4dKSbWymA%2BXViviLldu3ja3UB3sUoTI4DaPbFFgUc0%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

________________________________
The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by rczerminski-valo** [comment]
Still does not work :( - Here is what I did:
```
git pull
./buildDataWarriorOSX >& buildDataWarriorOSX.log
./runDataWarriorOSX >& runDataWarriorOSX.log
```
BTW: `build.sh `(or something along these lines) might help to streamline things a bit...

```
#!/bin/sh

OS=`uname`
case $OS in
  Darwin)
    tag="osx"
    TAG="OSX"
    ;;
  Linux)
    echo "TDB"
    ;;
  *)
      echo "ERROR: unknown OS= $OS"
      exit 1
    ;;
esac

mkdir ./bin
cp -r ./src/html ./bin/
cp -r ./src/images ./bin/
javac -d ./bin -sourcepath ./src:./stubs -classpath "./lib/*":./lib/${tag}/AppleJavaExtensions.jar src/com/actelion/research/datawarrior/DataWarrior${TAG}.java
rm -r ./bin/chemaxon
jar -cfm datawarrior.jar manifest_additions${TAG}.txt -C ./bin .
rm -rf ./bin
```


[buildDataWarriorOSX.log](https://github.com/thsa/datawarrior/files/9478339/buildDataWarriorOSX.log)
[runDataWarriorOSX.log](https://github.com/thsa/datawarrior/files/9478341/runDataWarriorOSX.log)

**Comment by thsa** [comment]
it seems, you are again missing JavaFX.

Just to confirm I cloned the project into a new directory and could run buildDataWarriorOSX and then runDataWarriorOSX without any trouble.
________________________________
Von: rczerminski-valo ***@***.***>
Gesendet: Freitag, 2. September 2022 15:48
An: thsa/datawarrior ***@***.***>
Cc: Thomas Sander ***@***.***>; Comment ***@***.***>
Betreff: Re: [thsa/datawarrior] add .tsv extension to DataWarrior compatible data files (Issue #9)


Still does not work :( - Here is what I did:

git pull
./buildDataWarriorOSX >& buildDataWarriorOSX.log
./runDataWarriorOSX >& runDataWarriorOSX.log


BTW: build.sh (or something along these lines) might help to streamline things a bit...

#!/bin/sh

OS=`uname`
case $OS in
  Darwin)
    tag="osx"
    TAG="OSX"
    ;;
  Linux)
    echo "TDB"
    ;;
  *)
      echo "ERROR: unknown OS= $OS"
      exit 1
    ;;
esac

mkdir ./bin
cp -r ./src/html ./bin/
cp -r ./src/images ./bin/
javac -d ./bin -sourcepath ./src:./stubs -classpath "./lib/*":./lib/${tag}/AppleJavaExtensions.jar src/com/actelion/research/datawarrior/DataWarrior${TAG}.java
rm -r ./bin/chemaxon
jar -cfm datawarrior.jar manifest_additions${TAG}.txt -C ./bin .
rm -rf ./bin


buildDataWarriorOSX.log<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Ffiles%2F9478339%2FbuildDataWarriorOSX.log&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ce7d4739a7ab545946bc908da8ce9e024%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637977233352411745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YPu7PFF1R9SIDp5a%2F1U3vwhtIOOlAOJTMTgQtZQDpOE%3D&reserved=0>
runDataWarriorOSX.log<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Ffiles%2F9478341%2FrunDataWarriorOSX.log&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ce7d4739a7ab545946bc908da8ce9e024%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637977233352411745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bIYyZO7AnSlcXpm9ypjSD6tGwtpzmbilQjW4ZLN0nK8%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fthsa%2Fdatawarrior%2Fissues%2F9%23issuecomment-1235528808&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ce7d4739a7ab545946bc908da8ce9e024%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637977233352411745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FSUts3jGiOkDGDBLV2zXwV0cTjdCVGKpQgjv%2FKts1zY%3D&reserved=0>, or unsubscribe<https://che01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACNFEBQ5S4IT7LPRFR7OZUDV4IAULANCNFSM6AAAAAAQBOGL2E&data=05%7C01%7Cthomas.sander%40idorsia.com%7Ce7d4739a7ab545946bc908da8ce9e024%7Cbb9214bf0cb941fdbd55d0c1c3eda110%7C0%7C0%7C637977233352411745%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=w4jZWKy3IrrtIVzJIKwVgSyUdI4wWKTpwKNzUc6NNg8%3D&reserved=0>.
You are receiving this because you commented.Message ID: ***@***.***>

________________________________
The information of this email and in any file transmitted with it is strictly confidential and may be legally privileged. It is intended solely for the addressee. If you are not the intended recipient, any copying, distribution or any other use of this email is prohibited and may be unlawful. In such case, you should please notify the sender immediately and destroy this email. The content of this email is not legally binding unless confirmed by letter. Any views expressed in this message are those of the individual sender, except where the message states otherwise and the sender is authorized to state them to be the views of the sender's company.

**Comment by rczerminski-valo** [comment]
My mistake, my "java" was pointing to the wrong location.
With `build.sh` and `run.sh` below, it works. Thanks!

build.sh:
```
#!/usr/local/bin/bash

OS=`uname`
declare -A OS_MAP=([Darwin]=OSX [Linux]=Linux)
OS_TAG=${OS_MAP[${OS}]}

if [ -z ${OS_TAG+x} ]; then
  echo "WARNING: unknown OS= ${OS}"
  exit 1
fi

if [ -z ${JAVA_HOME+x} ]; then
  if [ ${OS} == "Darwin" ]; then
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/liberica-jdk-8-full.jdk/Contents/Home
  elif [ ${OS} == "Linux" ]; then
    export JAVA_HOME="???"
  fi
fi

mkdir ./bin
cp -r ./src/{html,images} ./bin
$JAVA_HOME/bin/javac -d ./bin \
          -sourcepath ./src:./stubs \
          -classpath "./lib/*":./lib/${OS_TAG,,}/AppleJavaExtensions.jar \
          src/com/actelion/research/datawarrior/DataWarrior${OS_TAG}.java
rm -rf ./bin/chemaxon
$JAVA_HOME/bin/jar -cfm datawarrior.jar manifest_additions${OS_TAG}.txt -C ./bin .
rm -rf ./bin
```

run.sh:
```
#!/usr/local/bin/bash

OS=`uname`
declare -A OS_MAP=([Darwin]=OSX [Linux]=Linux)
OS_TAG=${OS_MAP[${OS}]}

if [ -z ${OS_TAG+x} ]; then
  echo "WARNING: unknown OS= ${OS}"
  exit 1
fi

if [ -z ${JAVA_HOME+x} ]; then
  if [ ${OS} == "Darwin" ]; then
    export JAVA_HOME=/Library/Java/JavaVirtualMachines/liberica-jdk-8-full.jdk/Contents/Home
  elif [ ${OS} == "Linux" ]; then
    export JAVA_HOME="???"
  fi
fi

if [ $OS == "Darwin" ]; then
  $JAVA_HOME/bin/java \
     -classpath "datawarrior.jar:./lib/*:./lib/${OS_TAG,,}/AppleJavaExtensions.jar" \
     com.actelion.research.datawarrior.DataWarrior${OS_TAG}
elif [ $OS == "Darwin" ]; then
  $JAVA_HOME/bin/java -classpath "datawarrior.jar:./lib/*" \
      com.actelion.research.datawarrior.DataWarriorLinux
else
   echo "ERROR: unknown OS= $OS"
   exit 1
fi

```
